"""alter precallplan tables

Revision ID: 02b3a5ccac75
Revises: 66392ab1e834
Create Date: 2025-04-16 17:19:12.228263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02b3a5ccac75'
down_revision: Union[str, None] = '66392ab1e834'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('precall_plan_forms', sa.Column('admin_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'precall_plan_forms', ['admin_id'])
    op.create_foreign_key(None, 'precall_plan_forms', 'user', ['admin_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'precall_plan_forms', type_='foreignkey')
    op.drop_constraint(None, 'precall_plan_forms', type_='unique')
    op.drop_column('precall_plan_forms', 'admin_id')
    # ### end Alembic commands ###
