"""add relationship in sceanarios

Revision ID: 06547dbfa336
Revises: 7e386dc63fb2
Create Date: 2025-03-24 18:32:41.772705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06547dbfa336'
down_revision: Union[str, None] = '7e386dc63fb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persona', sa.Column('last_updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('persona', 'updated_at')
    op.add_column('questions', sa.Column('last_updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('questions', 'updated_at')
    op.add_column('scenario_questions', sa.Column('last_updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('scenario_questions', 'updated_at')
    op.add_column('scenario_sales_reps', sa.Column('last_updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('scenario_sales_reps', 'updated_at')
    op.add_column('scenarios', sa.Column('last_updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('scenarios', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('scenarios', 'last_updated_at')
    op.add_column('scenario_sales_reps', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('scenario_sales_reps', 'last_updated_at')
    op.add_column('scenario_questions', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('scenario_questions', 'last_updated_at')
    op.add_column('questions', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('questions', 'last_updated_at')
    op.add_column('persona', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('persona', 'last_updated_at')
    # ### end Alembic commands ###
