"""added columns in scenario table

Revision ID: 068dffda2335
Revises: 11ab918940bb
Create Date: 2025-04-23 18:07:06.458755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '068dffda2335'
down_revision: Union[str, None] = '11ab918940bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('scenario_image', sa.String(), nullable=True))
    op.drop_column('scenarios', 'avatar_image')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('avatar_image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('scenarios', 'scenario_image')
    # ### end Alembic commands ###
