"""alter profile table

Revision ID: 0f5602a607d3
Revises: de4f07b10232
Create Date: 2025-04-29 17:00:56.985595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f5602a607d3'
down_revision: Union[str, None] = 'de4f07b10232'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP SEQUENCE IF EXISTS org_id_seq CASCADE")
    op.execute("CREATE SEQUENCE org_id_seq START WITH 100001 INCREMENT BY 1")
 
    # Then create the table using the sequence
    op.execute("DROP TABLE IF EXISTS organizations CASCADE;")

    # Then create the table using the sequence
    op.create_table(
        'organizations',
        sa.Column('id', sa.Integer(), server_default=sa.text("nextval('org_id_seq')"), primary_key=True),
        sa.Column('admin_id', sa.Integer(), nullable=False),
        sa.Column('master_prompt', sa.Text(), nullable=True),
        sa.Column('evaluation_prompt', sa.Text(), nullable=True),
        sa.Column('persona_prompt', sa.Text(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('created_by', sa.String(), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_by', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ondelete='CASCADE'),
        sa.UniqueConstraint('admin_id')
    )
    op.add_column('organizations', sa.Column('chatbot_prompt', sa.Text(), nullable=True))
    op.add_column('organizations', sa.Column('llm_model', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'llm_model')
    op.drop_column('organizations', 'chatbot_prompt')
    # ### end Alembic commands ###
