"""added columns in persona table

Revision ID: 11ab918940bb
Revises: 02b3a5ccac75
Create Date: 2025-04-23 16:52:32.316866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11ab918940bb'
down_revision: Union[str, None] = '02b3a5ccac75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persona', sa.Column('avatar_image', sa.String(), nullable=True))
    op.add_column('persona', sa.Column('thumbnail', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persona', 'thumbnail')
    op.drop_column('persona', 'avatar_image')
    # ### end Alembic commands ###
