"""add field manager column in users

Revision ID: 1f39420e0973
Revises: 97b89560a223
Create Date: 2025-12-18 16:29:30.715553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f39420e0973'
down_revision: Union[str, None] = '97b89560a223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('debrief_reports', 'ai_score',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.add_column('user', sa.Column('field_manager_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'user', ['field_manager_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'field_manager_id')
    op.alter_column('debrief_reports', 'ai_score',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
