"""added token columns

Revision ID: 21edd262755c
Revises: e831b7da3417
Create Date: 2026-02-10 16:22:32.637029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21edd262755c'
down_revision: Union[str, None] = 'e831b7da3417'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('debrief_reports', 'ai_score',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.add_column('user_monthly_credits', sa.Column('input_tokens_used', sa.BigInteger(), nullable=True))
    op.add_column('user_monthly_credits', sa.Column('output_tokens_used', sa.BigInteger(), nullable=True))
    op.add_column('user_monthly_credits', sa.Column('stt_minutes_used', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('user_monthly_credits', sa.Column('tts_minutes_used', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_monthly_credits', 'tts_minutes_used')
    op.drop_column('user_monthly_credits', 'stt_minutes_used')
    op.drop_column('user_monthly_credits', 'output_tokens_used')
    op.drop_column('user_monthly_credits', 'input_tokens_used')
    op.alter_column('debrief_reports', 'ai_score',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
