"""added boolean fields for email

Revision ID: 3522832ae713
Revises: 3f22499e61da
Create Date: 2026-02-19 16:26:29.919173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3522832ae713'
down_revision: Union[str, None] = '3f22499e61da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('debrief_reports', 'ai_score',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.add_column('user_monthly_credits', sa.Column('compute_warning_sent', sa.Boolean(), nullable=True))
    op.add_column('user_monthly_credits', sa.Column('compute_suspended_sent', sa.Boolean(), nullable=True))
    op.add_column('user_monthly_credits', sa.Column('avatar_warning_sent', sa.Boolean(), nullable=True))
    op.add_column('user_monthly_credits', sa.Column('avatar_suspended_sent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_monthly_credits', 'avatar_suspended_sent')
    op.drop_column('user_monthly_credits', 'avatar_warning_sent')
    op.drop_column('user_monthly_credits', 'compute_suspended_sent')
    op.drop_column('user_monthly_credits', 'compute_warning_sent')
    op.alter_column('debrief_reports', 'ai_score',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
