"""update column in company context table

Revision ID: 3a529c819885
Revises: ddfdcc4e9f82
Create Date: 2026-03-30 20:21:56.897875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a529c819885'
down_revision: Union[str, None] = 'ddfdcc4e9f82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('debrief_reports', 'ai_score',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.alter_column('organizations', 'evaluation_prompt',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizations', 'evaluation_prompt',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('debrief_reports', 'ai_score',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
