"""added org_id company context table

Revision ID: 3b7a16713e98
Revises: c47e623c1314
Create Date: 2026-03-30 14:54:44.459823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b7a16713e98'
down_revision: Union[str, None] = 'c47e623c1314'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_context', sa.Column('organization_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'company_context', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.alter_column('debrief_reports', 'ai_score',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('debrief_reports', 'ai_score',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_constraint(None, 'company_context', type_='foreignkey')
    op.drop_column('company_context', 'organization_id')
    # ### end Alembic commands ###
