"""updated column

Revision ID: 3f22499e61da
Revises: 21edd262755c
Create Date: 2026-02-18 16:52:46.274175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f22499e61da'
down_revision: Union[str, None] = '21edd262755c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_audit_logs', 'actor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('debrief_reports', 'ai_score',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('debrief_reports', 'ai_score',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('admin_audit_logs', 'actor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
