"""create roleplay's tables

Revision ID: 454f63890153
Revises: 62b531342267
Create Date: 2025-03-24 17:01:15.756457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '454f63890153'
down_revision: Union[str, None] = '62b531342267'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persona',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('primary_goal', sa.Text(), nullable=True),
    sa.Column('challenges', sa.Text(), nullable=True),
    sa.Column('objections', sa.Text(), nullable=True),
    sa.Column('motivations', sa.Text(), nullable=True),
    sa.Column('fears', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=256), nullable=True),
    sa.Column('last_updated_by', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=256), nullable=True),
    sa.Column('last_updated_by', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ai_trainer_opening', sa.Text(), nullable=True),
    sa.Column('selling_methodology', sa.Text(), nullable=True),
    sa.Column('persona_id', sa.Integer(), nullable=True),
    sa.Column('ideal_sales_outcome', sa.Text(), nullable=True),
    sa.Column('topics_to_cover', sa.Text(), nullable=True),
    sa.Column('current_state', sa.Text(), nullable=True),
    sa.Column('barriers_to_change', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=256), nullable=True),
    sa.Column('last_updated_by', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenario_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=256), nullable=True),
    sa.Column('last_updated_by', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenario_sales_reps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.Column('sales_rep_id', sa.Integer(), nullable=True),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sales_rep_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario_id', 'sales_rep_id', name='uq_scenario_sales_rep')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scenario_sales_reps')
    op.drop_table('scenario_questions')
    op.drop_table('scenarios')
    op.drop_table('questions')
    op.drop_table('persona')
    # ### end Alembic commands ###
