"""add new column content_create_access in user table 2

Revision ID: 50f1033d63b3
Revises: 868081bec7e6
Create Date: 2026-05-22 14:25:25.867230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50f1033d63b3'
down_revision: Union[str, None] = '868081bec7e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Existing autogenerated change
    op.alter_column(
        'debrief_reports',
        'ai_score',
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2),
        existing_nullable=True
    )

    # Backfill existing NULL values
    op.execute("""
        UPDATE "user"
        SET content_creator_access = TRUE
        WHERE content_creator_access IS NULL
    """)

    # Make column NOT NULL and set DB default TRUE
    op.alter_column(
        'user',
        'content_creator_access',
        existing_type=sa.BOOLEAN(),
        nullable=False,
        server_default=sa.true()
    )


def downgrade() -> None:
    """Downgrade schema."""

    # Remove NOT NULL + DEFAULT TRUE
    op.alter_column(
        'user',
        'content_creator_access',
        existing_type=sa.BOOLEAN(),
        nullable=True,
        server_default=None
    )

    # Existing autogenerated downgrade
    op.alter_column(
        'debrief_reports',
        'ai_score',
        existing_type=sa.Float(precision=2),
        type_=sa.REAL(),
        existing_nullable=True
    )
    # ### end Alembic commands ###
