"""adding field_intelligence_prompt

Revision ID: 522e2d5dbe71
Revises: 6b7906aa0d47
Create Date: 2026-06-19 17:52:15.700217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '522e2d5dbe71'
down_revision: Union[str, None] = '6b7906aa0d47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('debrief_reports', 'ai_score',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.add_column('organizations', sa.Column('field_intelligence_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'field_intelligence_prompt')
    op.alter_column('debrief_reports', 'ai_score',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
