"""update column in company context table

Revision ID: 523d111fa7bf
Revises: 3b7a16713e98
Create Date: 2026-03-30 15:49:44.089578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '523d111fa7bf'
down_revision: Union[str, None] = '3b7a16713e98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_context', sa.Column('organization_overview', sa.Text(), nullable=False))
    op.add_column('company_context', sa.Column('customer_segments', sa.Text(), nullable=False))
    op.add_column('company_context', sa.Column('int_user_ext_stakeholder', sa.Text(), nullable=False))
    op.add_column('company_context', sa.Column('brand_voice', sa.Text(), nullable=False))
    op.add_column('company_context', sa.Column('compliance_guardrails', sa.Text(), nullable=False))
    op.add_column('company_context', sa.Column('additional_context', sa.Text(), nullable=False))
    op.drop_column('company_context', 'customers_served')
    op.drop_column('company_context', 'company_name')
    op.drop_column('company_context', 'description')
    op.drop_column('company_context', 'constraints')
    op.drop_column('company_context', 'primary_user')
    op.drop_column('company_context', 'brand_guidelines')
    op.alter_column('debrief_reports', 'ai_score',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('debrief_reports', 'ai_score',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.add_column('company_context', sa.Column('brand_guidelines', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('company_context', sa.Column('primary_user', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('company_context', sa.Column('constraints', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('company_context', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('company_context', sa.Column('company_name', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.add_column('company_context', sa.Column('customers_served', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('company_context', 'additional_context')
    op.drop_column('company_context', 'compliance_guardrails')
    op.drop_column('company_context', 'brand_voice')
    op.drop_column('company_context', 'int_user_ext_stakeholder')
    op.drop_column('company_context', 'customer_segments')
    op.drop_column('company_context', 'organization_overview')
    # ### end Alembic commands ###
