"""alter profile table

Revision ID: 5b34fb243c7c
Revises: 7a4be0f4df4a
Create Date: 2025-04-29 15:59:43.643121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b34fb243c7c'
down_revision: Union[str, None] = '7a4be0f4df4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organizations')
    op.add_column('profile', sa.Column('full_name', sa.String(length=256), nullable=True))
    op.drop_column('profile', 'first_name')
    op.drop_column('profile', 'last_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('last_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('profile', sa.Column('first_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_column('profile', 'full_name')
    op.create_table('organizations',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('org_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('master_prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('evaluation_prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('persona_prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], name='organizations_admin_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='organizations_pkey'),
    sa.UniqueConstraint('admin_id', name='organizations_admin_id_key')
    )
    # ### end Alembic commands ###
