"""added prompt tables fix

Revision ID: 651246f45397
Revises: 52b25f260fa6
Create Date: 2026-05-19 21:14:40.448038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '651246f45397'
down_revision: Union[str, None] = '52b25f260fa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prompt_content', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=256), nullable=False),
    sa.Column('last_updated_by', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_master_id'), 'prompt_master', ['id'], unique=False)
    op.create_table('prompt_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('MESSAGING', 'OBJECTION_HANDLING', 'CASE_SUPPORT', 'TRAINING_DEPLOYMENT', 'LEADERSHIP', name='promptcategoryenum'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prompt_content', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=256), nullable=False),
    sa.Column('last_updated_by', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_user_id'), 'prompt_user', ['id'], unique=False)
    # op.drop_index('ix_user_prompts_id', table_name='user_prompts')
    # op.drop_index('ix_user_prompts_master_prompt_id', table_name='user_prompts')
    # op.drop_index('ix_user_prompts_user_id', table_name='user_prompts')
    # op.drop_table('user_prompts')
    op.alter_column('debrief_reports', 'ai_score',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('debrief_reports', 'ai_score',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.create_table('user_prompts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('master_prompt_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('prompt_content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('last_updated_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name='user_prompts_created_by_fkey'),
    sa.ForeignKeyConstraint(['last_updated_by'], ['user.id'], name='user_prompts_last_updated_by_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_prompts_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_prompts_pkey')
    )
    op.create_index('ix_user_prompts_user_id', 'user_prompts', ['user_id'], unique=False)
    op.create_index('ix_user_prompts_master_prompt_id', 'user_prompts', ['master_prompt_id'], unique=False)
    op.create_index('ix_user_prompts_id', 'user_prompts', ['id'], unique=False)
    op.drop_index(op.f('ix_prompt_user_id'), table_name='prompt_user')
    op.drop_table('prompt_user')
    op.drop_index(op.f('ix_prompt_master_id'), table_name='prompt_master')
    op.drop_table('prompt_master')
    # ### end Alembic commands ###
