"""added column in tokens

Revision ID: 6831f9b619ee
Revises: c949999a1157
Create Date: 2026-01-30 15:52:59.968383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6831f9b619ee'
down_revision: Union[str, None] = 'c949999a1157'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('debrief_reports', 'ai_score',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.add_column('user_monthly_credits', sa.Column('rollover_compute_credit', sa.Float(), nullable=True))
    op.add_column('user_monthly_credits', sa.Column('rollover_avatar_credit', sa.Float(), nullable=True))
    op.add_column('user_monthly_credits', sa.Column('bonus_compute_credit', sa.Float(), nullable=True))
    op.add_column('user_monthly_credits', sa.Column('bonus_avatar_credit', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_monthly_credits', 'bonus_avatar_credit')
    op.drop_column('user_monthly_credits', 'bonus_compute_credit')
    op.drop_column('user_monthly_credits', 'rollover_avatar_credit')
    op.drop_column('user_monthly_credits', 'rollover_compute_credit')
    op.alter_column('debrief_reports', 'ai_score',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
