"""added relations knowledgebase table

Revision ID: 695a6f8e437a
Revises: d5944599d32b
Create Date: 2025-05-05 16:35:53.259347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '695a6f8e437a'
down_revision: Union[str, None] = 'd5944599d32b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_base', sa.Column('name', sa.String(), nullable=False))
    op.add_column('knowledge_base', sa.Column('file_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_base', 'file_type')
    op.drop_column('knowledge_base', 'name')
    # ### end Alembic commands ###
