"""precallplan tables

Revision ID: 6c4e0fe96391
Revises: b6a59654c733
Create Date: 2025-05-13 16:35:28.771915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c4e0fe96391'
down_revision: Union[str, None] = 'b6a59654c733'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluation', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.add_column('evaluation', sa.Column('last_updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluation', 'last_updated_at')
    op.drop_column('evaluation', 'created_at')
    # ### end Alembic commands ###
