"""added filepath in precall

Revision ID: 6f2a3bf6341c
Revises: d3b15bcc3520
Create Date: 2025-05-22 17:53:06.491508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f2a3bf6341c'
down_revision: Union[str, None] = 'd3b15bcc3520'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('precall_prompt', sa.Text(), nullable=True))
    op.drop_column('organizations', 'persona_prompt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('persona_prompt', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('organizations', 'precall_prompt')
    # ### end Alembic commands ###
