"""added column in scenario

Revision ID: 76ae3b6bee0b
Revises: c55df1a116ea
Create Date: 2025-04-03 14:55:12.757906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76ae3b6bee0b'
down_revision: Union[str, None] = 'c55df1a116ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('critical_questions', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenarios', 'critical_questions')
    # ### end Alembic commands ###
