"""added debrief models

Revision ID: 7bf921d4489a
Revises: b370b7094ae4
Create Date: 2025-07-29 17:04:22.775773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bf921d4489a'
down_revision: Union[str, None] = 'b370b7094ae4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debrief_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('scenario_title', sa.String(), nullable=True),
    sa.Column('ai_score', sa.Integer(), nullable=True),
    sa.Column('pass_score', sa.Integer(), nullable=True),
    sa.Column('general_insights', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(length=256), nullable=True),
    sa.Column('last_updated_by', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['roleplay_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('debrief_skill_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('debrief_report_id', sa.Integer(), nullable=True),
    sa.Column('skill_name', sa.String(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['debrief_report_id'], ['debrief_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('debrief_skill_scores')
    op.drop_table('debrief_reports')
    # ### end Alembic commands ###
