"""created courses table

Revision ID: 82c4e98f48bc
Revises: 8dd2cce79b7d
Create Date: 2025-08-19 16:02:50.141488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82c4e98f48bc'
down_revision: Union[str, None] = '8dd2cce79b7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('image_url', sa.String(length=512), nullable=False))
    op.add_column('courses', sa.Column('course_file_url', sa.String(length=512), nullable=True))
    op.alter_column('debrief_reports', 'ai_score',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('debrief_reports', 'ai_score',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_column('courses', 'course_file_url')
    op.drop_column('courses', 'image_url')
    # ### end Alembic commands ###
