"""fixing migrations

Revision ID: 85295ed727ae
Revises: fc875a640b40
Create Date: 2026-06-03 15:43:45.795503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85295ed727ae'
down_revision: Union[str, None] = 'fc875a640b40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('debrief_reports', 'ai_score',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.alter_column('knowledge_base', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('knowledge_base', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('knowledge_base', 'updated_at')
    op.drop_column('knowledge_base', 'file_size')
    op.drop_column('knowledge_base', 'failure_stage')

    op.execute("""
        UPDATE knowledge_base
        SET status = 'completed'
        WHERE status IS NULL OR status = '';
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_base', sa.Column('failure_stage', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('knowledge_base', sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('knowledge_base', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.alter_column('knowledge_base', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('knowledge_base', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('debrief_reports', 'ai_score',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
