"""add new fields in knowledgebase modal

Revision ID: 91d46d80eb6c
Revises: 7708ce4672bf
Create Date: 2026-05-29 18:00:42.689326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91d46d80eb6c'
down_revision: Union[str, None] = '7708ce4672bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('debrief_reports', 'ai_score',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.add_column('knowledge_base', sa.Column('failure_reason', sa.Text(), nullable=True))
    op.add_column('knowledge_base', sa.Column('failure_stage', sa.String(), nullable=True))
    op.add_column('knowledge_base', sa.Column('file_size', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_base', 'file_size')
    op.drop_column('knowledge_base', 'failure_stage')
    op.drop_column('knowledge_base', 'failure_reason')
    op.alter_column('debrief_reports', 'ai_score',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
