"""Added new column to presona

Revision ID: 9284cc25e99b
Revises: 4103b65d7b8f
Create Date: 2025-05-30 17:43:24.803197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9284cc25e99b'
down_revision: Union[str, None] = '4103b65d7b8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persona', sa.Column('avatar_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persona', 'avatar_id')
    # ### end Alembic commands ###
