"""Make priority optional in knowledge_base

Revision ID: 951612b53352
Revises: 11fbb1c141e5
Create Date: 2025-05-29 15:42:46.400642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '951612b53352'
down_revision: Union[str, None] = '11fbb1c141e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knowledge_base', 'priority',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knowledge_base', 'priority',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
