"""added impersonation_log table

Revision ID: 9694e92cb008
Revises: 8f02710fe870
Create Date: 2025-09-15 16:45:25.126582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9694e92cb008'
down_revision: Union[str, None] = '8f02710fe870'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('impersonation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_email', sa.String(), nullable=False),
    sa.Column('subject_email', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_impersonation_logs_id'), 'impersonation_logs', ['id'], unique=False)
    op.alter_column('debrief_reports', 'ai_score',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('debrief_reports', 'ai_score',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_index(op.f('ix_impersonation_logs_id'), table_name='impersonation_logs')
    op.drop_table('impersonation_logs')
    # ### end Alembic commands ###
