"""fixed category column in prompt

Revision ID: b5fcbcf28b02
Revises: 7708ce4672bf
Create Date: 2026-06-02 17:52:51.427574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5fcbcf28b02'
down_revision: Union[str, None] = '7708ce4672bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('debrief_reports', 'ai_score',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.alter_column('prompt_user', 'category',
               existing_type=postgresql.ENUM('MESSAGING', 'OBJECTION_HANDLING', 'CASE_SUPPORT', 'TRAINING_DEPLOYMENT', 'LEADERSHIP', name='promptcategoryenum'),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prompt_user', 'category',
               existing_type=sa.String(length=255),
               type_=postgresql.ENUM('MESSAGING', 'OBJECTION_HANDLING', 'CASE_SUPPORT', 'TRAINING_DEPLOYMENT', 'LEADERSHIP', name='promptcategoryenum'),
               existing_nullable=False)
    op.alter_column('debrief_reports', 'ai_score',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
