"""added company context table

Revision ID: c47e623c1314
Revises: 3522832ae713
Create Date: 2026-03-27 21:04:57.948473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c47e623c1314'
down_revision: Union[str, None] = '3522832ae713'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_context',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('customers_served', sa.Text(), nullable=False),
    sa.Column('primary_user', sa.Text(), nullable=False),
    sa.Column('brand_guidelines', sa.Text(), nullable=False),
    sa.Column('constraints', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('last_updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_by', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_context_id'), 'company_context', ['id'], unique=False)
    op.alter_column('debrief_reports', 'ai_score',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('debrief_reports', 'ai_score',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_index(op.f('ix_company_context_id'), table_name='company_context')
    op.drop_table('company_context')
    # ### end Alembic commands ###
