"""added columns in persona

Revision ID: c73f90cc7196
Revises: d066e980fae2
Create Date: 2025-03-27 14:59:45.011468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c73f90cc7196'
down_revision: Union[str, None] = 'd066e980fae2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persona', sa.Column('communication_style', sa.Text(), nullable=True))
    op.add_column('persona', sa.Column('behavioral_tendencies', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persona', 'behavioral_tendencies')
    op.drop_column('persona', 'communication_style')
    # ### end Alembic commands ###
