"""add column uploaded at

Revision ID: c866ec93bf2c
Revises: 91d46d80eb6c
Create Date: 2026-06-01 13:18:52.671105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c866ec93bf2c'
down_revision: Union[str, None] = '91d46d80eb6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('debrief_reports', 'ai_score',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.add_column('knowledge_base', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('knowledge_base', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('knowledge_base', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('knowledge_base', 'file_size',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_column('knowledge_base', 'failure_reason')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_base', sa.Column('failure_reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('knowledge_base', 'file_size',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('knowledge_base', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('knowledge_base', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('knowledge_base', 'updated_at')
    op.alter_column('debrief_reports', 'ai_score',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
