"""added global credit and usercredit

Revision ID: c949999a1157
Revises: d4e2cf860c72
Create Date: 2026-01-27 18:14:51.721247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c949999a1157'
down_revision: Union[str, None] = 'd4e2cf860c72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_credit_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monthly_compute_credit', sa.Integer(), nullable=False),
    sa.Column('monthly_avatar_credit', sa.Integer(), nullable=False),
    sa.Column('input_tokens_per_credit', sa.Integer(), nullable=False),
    sa.Column('output_tokens_per_credit', sa.Integer(), nullable=False),
    sa.Column('stt_minutes_per_credit', sa.Integer(), nullable=False),
    sa.Column('tts_minutes_per_credit', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_global_credit_settings_id'), 'global_credit_settings', ['id'], unique=False)
    op.create_table('admin_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('actor_role', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('audit_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_audit_logs_id'), 'admin_audit_logs', ['id'], unique=False)
    op.create_table('user_monthly_credits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('compute_credit_allocated', sa.Float(), nullable=False),
    sa.Column('avatar_credit_allocated', sa.Float(), nullable=False),
    sa.Column('compute_credit_used', sa.Float(), nullable=True),
    sa.Column('avatar_credit_used', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_monthly_credits_id'), 'user_monthly_credits', ['id'], unique=False)
    op.alter_column('debrief_reports', 'ai_score',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('debrief_reports', 'ai_score',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_index(op.f('ix_user_monthly_credits_id'), table_name='user_monthly_credits')
    op.drop_table('user_monthly_credits')
    op.drop_index(op.f('ix_admin_audit_logs_id'), table_name='admin_audit_logs')
    op.drop_table('admin_audit_logs')
    op.drop_index(op.f('ix_global_credit_settings_id'), table_name='global_credit_settings')
    op.drop_table('global_credit_settings')
    # ### end Alembic commands ###
