"""Add bot_state_id to roleplay_sessions

Revision ID: ca5b55e80901
Revises: 1db74561cc57
Create Date: 2025-10-27 17:00:07.141773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca5b55e80901'
down_revision: Union[str, None] = '1db74561cc57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('debrief_reports', 'ai_score',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.add_column('roleplay_sessions', sa.Column('bot_state_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roleplay_sessions', 'bot_state_id')
    op.alter_column('debrief_reports', 'ai_score',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
