"""added filepath in precall

Revision ID: d3b15bcc3520
Revises: 6c4e0fe96391
Create Date: 2025-05-20 15:14:18.412955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3b15bcc3520'
down_revision: Union[str, None] = '6c4e0fe96391'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('precall_plan_forms', sa.Column('file_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('precall_plan_forms', 'file_path')
    # ### end Alembic commands ###
