"""added fields in org table

Revision ID: db203178497b
Revises: cd3c8335b9a1
Create Date: 2025-08-13 15:43:34.384522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db203178497b'
down_revision: Union[str, None] = 'cd3c8335b9a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('debrief_reports', 'ai_score',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.add_column('organizations', sa.Column('courses_prompt', sa.Text(), nullable=True))
    op.add_column('organizations', sa.Column('email_prompt', sa.Text(), nullable=True))
    op.add_column('organizations', sa.Column('summarizer_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'summarizer_prompt')
    op.drop_column('organizations', 'email_prompt')
    op.drop_column('organizations', 'courses_prompt')
    op.alter_column('debrief_reports', 'ai_score',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
