"""added column in scenario

Revision ID: db4703362b8e
Revises: 9f74d307c186
Create Date: 2025-04-03 20:48:05.994409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db4703362b8e'
down_revision: Union[str, None] = '9f74d307c186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('evaluation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'scenarios', 'evaluation', ['evaluation_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scenarios', type_='foreignkey')
    op.drop_column('scenarios', 'evaluation_id')
    # ### end Alembic commands ###
