"""add icon and icon_source column in prompt_master and prompt_user table

Revision ID: e15cb41018ff
Revises: 6b7906aa0d47
Create Date: 2026-06-16 15:39:18.050581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e15cb41018ff'
down_revision: Union[str, None] = '6b7906aa0d47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('debrief_reports', 'ai_score',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.add_column('prompt_master', sa.Column('icon', sa.String(length=256), nullable=True))
    op.add_column('prompt_user', sa.Column('icon', sa.String(length=256), nullable=True))
    op.add_column('prompt_user', sa.Column('icon_source', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompt_user', 'icon_source')
    op.drop_column('prompt_user', 'icon')
    op.drop_column('prompt_master', 'icon')
    op.alter_column('debrief_reports', 'ai_score',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
