"""added column in usercredit

Revision ID: e831b7da3417
Revises: d9c1caf5fd52
Create Date: 2026-02-04 15:50:47.637108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e831b7da3417'
down_revision: Union[str, None] = 'd9c1caf5fd52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('debrief_reports', 'ai_score',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.add_column('user_monthly_credits', sa.Column('compute_access', sa.Boolean(), nullable=True))
    op.add_column('user_monthly_credits', sa.Column('avatar_access', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_monthly_credits', 'avatar_access')
    op.drop_column('user_monthly_credits', 'compute_access')
    op.alter_column('debrief_reports', 'ai_score',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
