"""alter profile table

Revision ID: fa561140ec76
Revises: 0f5602a607d3
Create Date: 2025-04-29 17:02:32.406252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa561140ec76'
down_revision: Union[str, None] = '0f5602a607d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('last_updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('organizations', sa.Column('last_updated_by', sa.String(), nullable=False))
    op.drop_column('organizations', 'updated_by')
    op.drop_column('organizations', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('organizations', sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('organizations', 'last_updated_by')
    op.drop_column('organizations', 'last_updated_at')
    # ### end Alembic commands ###
