"""added soft delete in courses, scenario

Revision ID: fc202b42b124
Revises: 1f39420e0973
Create Date: 2025-12-19 18:52:04.900890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc202b42b124'
down_revision: Union[str, None] = '1f39420e0973'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "courses",
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            server_default=sa.false(),   # 👈 CRITICAL
            nullable=False
        )
    )

    op.add_column(
        "courses",
        sa.Column(
            "deleted_at",
            sa.DateTime(),
            nullable=True
        )
    )

    # Remove default after backfill
    op.alter_column(
        "courses",
        "is_deleted",
        server_default=None
    )

    # ===== EXISTING CHANGE =====
    op.alter_column(
        "debrief_reports",
        "ai_score",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2),
        existing_nullable=True
    )

    # ===== SCENARIOS =====
    op.add_column(
        "scenarios",
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            server_default=sa.false(),   # 👈 CRITICAL
            nullable=False
        )
    )

    op.add_column(
        "scenarios",
        sa.Column(
            "deleted_at",
            sa.DateTime(),
            nullable=True
        )
    )

    # Remove default after backfill
    op.alter_column(
        "scenarios",
        "is_deleted",
        server_default=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenarios', 'deleted_at')
    op.drop_column('scenarios', 'is_deleted')
    op.alter_column('debrief_reports', 'ai_score',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_column('courses', 'deleted_at')
    op.drop_column('courses', 'is_deleted')
    # ### end Alembic commands ###
